import 'dotenv/config';

export default {
  PORT: process.env.PORT ?? 3000,
  NOTION_TOKEN: process.env.NOTION_TOKEN,
  NOTION_TASKS_DATABASE: process.env.NOTION_TASKS_DATABASE,
  NOTION_PROJECTS_DATABASE: process.env.NOTION_PROJECTS_DATABASE,
  NOTION_LABELS_DATABASE: process.env.NOTION_LABELS_DATABASE,
  TODOIST_CLIENT_SECRET: process.env.TODOIST_CLIENT_SECRET,
  TODOIST_OAUTH_URL: process.env.TODOIST_OAUTH_URL,
  TODOIST_CLIENT_ID: process.env.TODOIST_CLIENT_ID,
  TIMEZONE: process.env.TIMEZONE,
  REDISCLOUD_URL: process.env.REDISCLOUD_URL,
};
