import 'dotenv/config';

export default {
  PORT: process.env.PORT ?? 3000,
  NOTION_TOKEN: process.env.NOTION_TOKEN,
  TODOIST_API_TOKEN: process.env.TODOIST_API_TOKEN,
  NOTION_TASKS_DATABASE: process.env.NOTION_TASKS_DATABASE,
  NOTION_PROJECTS_DATABASE: process.env.NOTION_PROJECTS_DATABASE,
  NOTION_LABELS_DATABASE: process.env.NOTION_LABELS_DATABASE,
  TODOIST_CLIENT_SECRET: process.env.TODOIST_CLIENT_SECRET,
};
